"""outbound dispatch ledger and send limits

Revision ID: 487fe7f1b98f
Revises: d4ee9ddac4cf
Create Date: 2026-10-02 06:30:00.881720

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "487fe7f1b98f"
down_revision: Union[str, Sequence[str], None] = "d4ee9ddac4cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbound_messages",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.String(), server_default="email", nullable=False),
        sa.Column("to_email", postgresql.CITEXT(), nullable=True),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("adapter", sa.String(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("provider_message_id", sa.String(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("channel IN ('email')", name=op.f("ck_outbound_messages_channel")),
        sa.CheckConstraint("status IN ('sent','failed','bounced','replied')", name=op.f("ck_outbound_messages_status")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_outbound_messages_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["message_drafts.id"],
            name=op.f("fk_outbound_messages_draft_id_message_drafts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_outbound_messages_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_messages")),
    )
    op.create_index(
        "ix_outbound_messages_account_dispatched",
        "outbound_messages",
        ["account_id", sa.literal_column("dispatched_at DESC")],
        unique=False,
    )
    op.create_index("ix_outbound_messages_lead", "outbound_messages", ["lead_id"], unique=False)
    op.create_index(
        "uq_outbound_messages_account_idempotency", "outbound_messages", ["account_id", "idempotency_key"], unique=True
    )
    op.create_table(
        "outbound_events",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("clock_timestamp()"), nullable=False
        ),
        sa.CheckConstraint(
            "event_type IN ('sent','failed','bounced','replied','opted_out')",
            name=op.f("ck_outbound_events_event_type"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_outbound_events_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["outbound_messages.id"],
            name=op.f("fk_outbound_events_message_id_outbound_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_events")),
    )
    op.create_index("ix_outbound_events_message_created", "outbound_events", ["message_id", "created_at"], unique=False)
    op.add_column("send_policies", sa.Column("max_per_day", sa.Integer(), server_default="20", nullable=False))
    op.add_column("send_policies", sa.Column("min_delay_seconds", sa.Integer(), server_default="60", nullable=False))
    op.add_column(
        "send_policies", sa.Column("sending_paused", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # CHECK constraints are not detected by Alembic: written by hand, with short names (the naming
    # convention adds the ck_<table>_ prefix).
    op.create_check_constraint("max_per_day", "send_policies", "max_per_day BETWEEN 0 AND 100000")
    op.create_check_constraint("min_delay_seconds", "send_policies", "min_delay_seconds BETWEEN 0 AND 86400")
    op.drop_constraint(op.f("ck_usage_records_kind"), "usage_records", type_="check")
    op.create_check_constraint(
        "kind", "usage_records", "kind IN ('discovery_run','signals_analyzed','drafts_generated','messages_dispatched')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_usage_records_kind"), "usage_records", type_="check")
    op.execute("DELETE FROM usage_records WHERE kind = 'messages_dispatched'")  # would violate the old CHECK
    op.create_check_constraint(
        "kind", "usage_records", "kind IN ('discovery_run','signals_analyzed','drafts_generated')"
    )
    op.drop_constraint(op.f("ck_send_policies_min_delay_seconds"), "send_policies", type_="check")
    op.drop_constraint(op.f("ck_send_policies_max_per_day"), "send_policies", type_="check")
    op.drop_column("send_policies", "sending_paused")
    op.drop_column("send_policies", "min_delay_seconds")
    op.drop_column("send_policies", "max_per_day")
    op.drop_index("ix_outbound_events_message_created", table_name="outbound_events")
    op.drop_table("outbound_events")
    op.drop_index("uq_outbound_messages_account_idempotency", table_name="outbound_messages")
    op.drop_index("ix_outbound_messages_lead", table_name="outbound_messages")
    op.drop_index("ix_outbound_messages_account_dispatched", table_name="outbound_messages")
    op.drop_table("outbound_messages")
    # ### end Alembic commands ###
