"""prospect import batches

Revision ID: c303c1bc427f
Revises: a7c1e9d3b5f2
Create Date: 2026-10-03 04:43:37.915450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c303c1bc427f"
down_revision: Union[str, Sequence[str], None] = "a7c1e9d3b5f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prospect_import_batches",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("content_sha256", sa.String(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("legal_basis", sa.String(), nullable=False),
        sa.Column("legal_basis_note", sa.Text(), nullable=True),
        sa.Column("country", sa.String(), server_default="FR", nullable=False),
        sa.Column("language", sa.String(), server_default="fr", nullable=False),
        sa.Column("rows_total", sa.Integer(), nullable=False),
        sa.Column(
            "summary", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("format IN ('csv','json')", name=op.f("ck_prospect_import_batches_format")),
        sa.CheckConstraint(
            "legal_basis IN ('legitimate_interest_b2b','consent','contract','other')",
            name=op.f("ck_prospect_import_batches_legal_basis"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_prospect_import_batches_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_prospect_import_batches_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospect_import_batches")),
    )
    op.create_index(
        "ix_prospect_import_batches_account_created",
        "prospect_import_batches",
        ["account_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_prospect_import_batches_source", "prospect_import_batches", ["account_id", "source_name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_prospect_import_batches_source", table_name="prospect_import_batches")
    op.drop_index("ix_prospect_import_batches_account_created", table_name="prospect_import_batches")
    op.drop_table("prospect_import_batches")
    # ### end Alembic commands ###
