"""initial schema

Revision ID: c3bad547cfc1
Revises:
Create Date: 2026-07-07 10:26:32.025070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3bad547cfc1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required by UUIDPKMixin (gen_random_uuid()) and the CITEXT email columns —
    # not autodetected by autogenerate since they aren't SQLAlchemy table objects.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("plan", sa.String(), server_default="pro", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("plan IN ('free','pro','enterprise')", name=op.f("ck_accounts_plan")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_table(
        "webhook_events",
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint("provider IN ('sendgrid','twilio')", name=op.f("ck_webhook_events_provider")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
    )
    op.create_index(
        "ix_webhook_events_unprocessed",
        "webhook_events",
        ["received_at"],
        unique=False,
        postgresql_where=sa.text("processed = false"),
    )
    op.create_table(
        "agents",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), server_default="outreach", nullable=False),
        sa.Column("status", sa.String(), server_default="idle", nullable=False),
        sa.Column("tasks_completed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tasks_in_queue", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('outreach','enrichment','scraper','responder')", name=op.f("ck_agents_role")),
        sa.CheckConstraint("status IN ('idle','running','paused','error')", name=op.f("ck_agents_status")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_agents_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
    )
    op.create_table(
        "lead_sources",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), server_default="manual", nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('manual','csv_import','scraper','api','enrichment','referral')", name=op.f("ck_lead_sources_kind")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_lead_sources_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_sources")),
    )
    op.create_index("uq_lead_sources_account_name", "lead_sources", ["account_id", "name"], unique=True)
    op.create_table(
        "segments",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "definition", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("is_dynamic", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_segments_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_segments")),
    )
    op.create_index(
        "uq_segments_account_name",
        "segments",
        ["account_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "send_policies",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("max_per_hour", sa.Integer(), server_default="100", nullable=False),
        sa.Column("window_start_hour", sa.Integer(), server_default="8", nullable=False),
        sa.Column("window_end_hour", sa.Integer(), server_default="18", nullable=False),
        sa.Column("timezone_source", sa.String(), server_default="lead_country", nullable=False),
        sa.Column("account_default_timezone", sa.String(), server_default="UTC", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("channel IN ('email','whatsapp')", name=op.f("ck_send_policies_channel")),
        sa.CheckConstraint(
            "timezone_source IN ('lead_country','account_default')", name=op.f("ck_send_policies_tz_source")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_send_policies_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_send_policies")),
    )
    op.create_index("uq_send_policies_account_channel", "send_policies", ["account_id", "channel"], unique=True)
    op.create_table(
        "tags",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_tags_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
    )
    op.create_index("uq_tags_account_name", "tags", ["account_id", "name"], unique=True)
    op.create_table(
        "users",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), server_default="owner", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("role IN ('owner','admin','member')", name=op.f("ck_users_role")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_users_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_account_id"), "users", ["account_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(), server_default="user", nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("actor_type IN ('user','system','celery_task')", name=op.f("ck_audit_logs_actor_type")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_audit_logs_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_account_created",
        "audit_logs",
        ["account_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "campaigns",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), server_default="draft", nullable=False),
        sa.Column("channels", postgresql.ARRAY(sa.String()), server_default=sa.text("'{email}'"), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("sent", sa.Integer(), server_default="0", nullable=False),
        sa.Column("opened", sa.Integer(), server_default="0", nullable=False),
        sa.Column("replied", sa.Integer(), server_default="0", nullable=False),
        sa.Column("converted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('draft','running','paused','completed')", name=op.f("ck_campaigns_status")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_campaigns_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_campaigns_agent_id_agents"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index(op.f("ix_campaigns_account_id"), "campaigns", ["account_id"], unique=False)
    op.create_table(
        "leads",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("language", sa.String(), server_default="en", nullable=False),
        sa.Column("stage", sa.String(), server_default="new", nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "stage IN ('new','contacted','engaged','qualified','won','lost')", name=op.f("ck_leads_stage")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_leads_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["lead_sources.id"], name=op.f("fk_leads_source_id_lead_sources"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
    )
    op.create_index(
        "ix_leads_account_created", "leads", ["account_id", sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index(
        "ix_leads_account_score",
        "leads",
        ["account_id", sa.literal_column("score DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_leads_account_stage",
        "leads",
        ["account_id", "stage"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("ix_leads_tags_gin", "leads", ["tags"], unique=False, postgresql_using="gin")
    op.create_index(
        "uq_leads_account_email",
        "leads",
        ["account_id", "email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND email IS NOT NULL"),
    )
    op.create_table(
        "campaign_leads",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name=op.f("fk_campaign_leads_campaign_id_campaigns"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_campaign_leads_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("campaign_id", "lead_id", name=op.f("pk_campaign_leads")),
    )
    op.create_index("ix_campaign_leads_lead", "campaign_leads", ["lead_id"], unique=False)
    op.create_table(
        "campaign_steps",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(), server_default="email", nullable=False),
        sa.Column("delay_hours", sa.Integer(), server_default="0", nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("body", sa.Text(), server_default="", nullable=False),
        sa.Column("language", sa.String(), server_default="en", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("channel IN ('email','whatsapp')", name=op.f("ck_campaign_steps_channel")),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name=op.f("fk_campaign_steps_campaign_id_campaigns"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_steps")),
    )
    op.create_index("uq_campaign_steps_campaign_index", "campaign_steps", ["campaign_id", "step_index"], unique=True)
    op.create_table(
        "contacts",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("role_title", sa.String(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_contacts_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], name=op.f("fk_contacts_lead_id_leads"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_index(
        "uq_contacts_lead_email",
        "contacts",
        ["lead_id", "email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND email IS NOT NULL"),
    )
    op.create_table(
        "lead_scores",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("computed_by", sa.String(), server_default="system", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("computed_by IN ('system','celery_task','manual')", name=op.f("ck_lead_scores_computed_by")),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_lead_scores_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_scores")),
    )
    op.create_index(
        "ix_lead_scores_lead_created", "lead_scores", ["lead_id", sa.literal_column("created_at DESC")], unique=False
    )
    op.create_table(
        "lead_tags",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], name=op.f("fk_lead_tags_lead_id_leads"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], name=op.f("fk_lead_tags_tag_id_tags"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("lead_id", "tag_id", name=op.f("pk_lead_tags")),
    )
    op.create_table(
        "notes",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("author_user_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("lead_id IS NOT NULL OR campaign_id IS NOT NULL", name=op.f("ck_notes_target")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_notes_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"], ["users.id"], name=op.f("fk_notes_author_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name=op.f("fk_notes_campaign_id_campaigns"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], name=op.f("fk_notes_lead_id_leads"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    op.create_table(
        "tasks",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("assigned_to_user_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="open", nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('open','in_progress','done','cancelled')", name=op.f("ck_tasks_status")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_tasks_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"], ["users.id"], name=op.f("fk_tasks_assigned_to_user_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name=op.f("fk_tasks_campaign_id_campaigns"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["lead_id"], ["leads.id"], name=op.f("fk_tasks_lead_id_leads"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(
        "ix_tasks_account_status",
        "tasks",
        ["account_id", "status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "consent_current",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], name=op.f("fk_consent_current_contact_id_contacts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("contact_id", "channel", name=op.f("pk_consent_current")),
    )
    op.create_table(
        "consent_records",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("recorded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("channel IN ('email','whatsapp')", name=op.f("ck_consent_records_channel")),
        sa.CheckConstraint("status IN ('opted_in','opted_out','unknown')", name=op.f("ck_consent_records_status")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_consent_records_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], name=op.f("fk_consent_records_contact_id_contacts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_records")),
    )
    op.create_index(
        "ix_consent_records_contact_channel",
        "consent_records",
        ["contact_id", "channel", sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    op.create_table(
        "email_sends",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("campaign_step_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("to_email", postgresql.CITEXT(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), server_default="queued", nullable=False),
        sa.Column("provider", sa.String(), server_default="sendgrid", nullable=False),
        sa.Column("provider_message_id", sa.String(), nullable=True),
        sa.Column(
            "provider_message_id_base",
            sa.String(),
            sa.Computed("split_part(provider_message_id, '.', 1)", persisted=True),
            nullable=True,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued','sent','delivered','opened','clicked','replied','bounced','failed','mock')",
            name=op.f("ck_email_sends_status"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_email_sends_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name=op.f("fk_email_sends_campaign_id_campaigns"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_step_id"],
            ["campaign_steps.id"],
            name=op.f("fk_email_sends_campaign_step_id_campaign_steps"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], name=op.f("fk_email_sends_contact_id_contacts"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_sends")),
    )
    op.create_index("ix_email_sends_provider_id_base", "email_sends", ["provider_message_id_base"], unique=False)
    op.create_index(op.f("ix_email_sends_provider_message_id"), "email_sends", ["provider_message_id"], unique=False)
    op.create_table(
        "outreach_events",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("campaign_step_id", sa.UUID(), nullable=True),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), server_default="outbound", nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "meta", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("channel IN ('email','whatsapp')", name=op.f("ck_outreach_events_channel")),
        sa.CheckConstraint("direction IN ('outbound','inbound')", name=op.f("ck_outreach_events_direction")),
        sa.CheckConstraint(
            "event_type IN ('queued','sent','delivered','opened','clicked','replied','bounced','failed','opted_out')",
            name=op.f("ck_outreach_events_event_type"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_outreach_events_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_outreach_events_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_step_id"],
            ["campaign_steps.id"],
            name=op.f("fk_outreach_events_campaign_step_id_campaign_steps"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], name=op.f("fk_outreach_events_contact_id_contacts"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_outreach_events_lead_id_leads"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_events")),
    )
    op.create_index(
        "ix_outreach_events_account_time",
        "outreach_events",
        ["account_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index("ix_outreach_events_campaign_type", "outreach_events", ["campaign_id", "event_type"], unique=False)
    op.create_table(
        "whatsapp_sends",
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("from_number", sa.String(), nullable=False),
        sa.Column("to_number", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), server_default="queued", nullable=False),
        sa.Column("provider", sa.String(), server_default="twilio", nullable=False),
        sa.Column("provider_message_sid", sa.String(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("direction IN ('outbound','inbound')", name=op.f("ck_whatsapp_sends_direction")),
        sa.CheckConstraint(
            "status IN ('queued','sent','delivered','opened','replied','failed','mock')",
            name=op.f("ck_whatsapp_sends_status"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_whatsapp_sends_account_id_accounts"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["campaigns.id"], name=op.f("fk_whatsapp_sends_campaign_id_campaigns"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"], ["contacts.id"], name=op.f("fk_whatsapp_sends_contact_id_contacts"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whatsapp_sends")),
    )
    op.create_index(op.f("ix_whatsapp_sends_contact_id"), "whatsapp_sends", ["contact_id"], unique=False)
    op.create_index(op.f("ix_whatsapp_sends_from_number"), "whatsapp_sends", ["from_number"], unique=False)
    op.create_index(
        op.f("ix_whatsapp_sends_provider_message_sid"), "whatsapp_sends", ["provider_message_sid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_whatsapp_sends_provider_message_sid"), table_name="whatsapp_sends")
    op.drop_index(op.f("ix_whatsapp_sends_from_number"), table_name="whatsapp_sends")
    op.drop_index(op.f("ix_whatsapp_sends_contact_id"), table_name="whatsapp_sends")
    op.drop_table("whatsapp_sends")
    op.drop_index("ix_outreach_events_campaign_type", table_name="outreach_events")
    op.drop_index("ix_outreach_events_account_time", table_name="outreach_events")
    op.drop_table("outreach_events")
    op.drop_index(op.f("ix_email_sends_provider_message_id"), table_name="email_sends")
    op.drop_index("ix_email_sends_provider_id_base", table_name="email_sends")
    op.drop_table("email_sends")
    op.drop_index("ix_consent_records_contact_channel", table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_table("consent_current")
    op.drop_index("ix_tasks_account_status", table_name="tasks", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_table("tasks")
    op.drop_table("notes")
    op.drop_table("lead_tags")
    op.drop_index("ix_lead_scores_lead_created", table_name="lead_scores")
    op.drop_table("lead_scores")
    op.drop_index(
        "uq_contacts_lead_email",
        table_name="contacts",
        postgresql_where=sa.text("deleted_at IS NULL AND email IS NOT NULL"),
    )
    op.drop_table("contacts")
    op.drop_index("uq_campaign_steps_campaign_index", table_name="campaign_steps")
    op.drop_table("campaign_steps")
    op.drop_index("ix_campaign_leads_lead", table_name="campaign_leads")
    op.drop_table("campaign_leads")
    op.drop_index(
        "uq_leads_account_email",
        table_name="leads",
        postgresql_where=sa.text("deleted_at IS NULL AND email IS NOT NULL"),
    )
    op.drop_index("ix_leads_tags_gin", table_name="leads", postgresql_using="gin")
    op.drop_index("ix_leads_account_stage", table_name="leads", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_index("ix_leads_account_score", table_name="leads", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_index("ix_leads_account_created", table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_campaigns_account_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index("ix_audit_logs_account_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_account_id"), table_name="users")
    op.drop_table("users")
    op.drop_index("uq_tags_account_name", table_name="tags")
    op.drop_table("tags")
    op.drop_index("uq_send_policies_account_channel", table_name="send_policies")
    op.drop_table("send_policies")
    op.drop_index("uq_segments_account_name", table_name="segments", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_table("segments")
    op.drop_index("uq_lead_sources_account_name", table_name="lead_sources")
    op.drop_table("lead_sources")
    op.drop_table("agents")
    op.drop_index(
        "ix_webhook_events_unprocessed", table_name="webhook_events", postgresql_where=sa.text("processed = false")
    )
    op.drop_table("webhook_events")
    op.drop_table("accounts")
    op.execute("DROP EXTENSION IF EXISTS citext")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
    # ### end Alembic commands ###
