"""outreachos prospect discovery

Revision ID: d4ee9ddac4cf
Revises: c3bad547cfc1
Create Date: 2026-10-02 05:57:59.034686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4ee9ddac4cf"
down_revision: Union[str, Sequence[str], None] = "c3bad547cfc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppression_entries",
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("identity_hash", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('email','phone','domain')", name=op.f("ck_suppression_entries_kind")),
        sa.CheckConstraint(
            "reason IN ('opt_out','erasure','bounce','manual')", name=op.f("ck_suppression_entries_reason")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_suppression_entries_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppression_entries")),
    )
    op.create_index(
        "uq_suppression_entries_identity", "suppression_entries", ["account_id", "kind", "identity_hash"], unique=True
    )
    op.create_table(
        "usage_records",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "meta", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('discovery_run','signals_analyzed','drafts_generated')", name=op.f("ck_usage_records_kind")
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_usage_records_quantity")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_usage_records_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_records")),
    )
    op.create_index(
        "ix_usage_records_account_created",
        "usage_records",
        ["account_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "score_versions",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("config_hash", sa.String(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_score_versions_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_score_versions_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_versions")),
    )
    op.create_index("ix_score_versions_account_hash", "score_versions", ["account_id", "config_hash"], unique=False)
    op.create_index("uq_score_versions_account_version", "score_versions", ["account_id", "version"], unique=True)
    op.create_table(
        "prospect_scores",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("score_version_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("coverage", sa.Float(), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name=op.f("ck_prospect_scores_range")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_prospect_scores_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_prospect_scores_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["score_version_id"],
            ["score_versions.id"],
            name=op.f("fk_prospect_scores_score_version_id_score_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospect_scores")),
    )
    op.create_index(
        "ix_prospect_scores_lead_created",
        "prospect_scores",
        ["lead_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "prospect_sources",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("license_note", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column(
            "fields", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_prospect_sources_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_prospect_sources_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospect_sources")),
    )
    op.create_index("ix_prospect_sources_lead", "prospect_sources", ["lead_id"], unique=False)
    op.create_index(
        "uq_prospect_sources_listing_version",
        "prospect_sources",
        ["account_id", "source_name", "external_id", "content_hash"],
        unique=True,
    )
    op.create_table(
        "message_drafts",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("campaign_step_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.String(), server_default="email", nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "facts", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("template_version", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="draft", nullable=False),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("channel IN ('email')", name=op.f("ck_message_drafts_channel")),
        sa.CheckConstraint("status IN ('draft','approved','rejected')", name=op.f("ck_message_drafts_status")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_message_drafts_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_step_id"],
            ["campaign_steps.id"],
            name=op.f("fk_message_drafts_campaign_step_id_campaign_steps"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_message_drafts_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_message_drafts_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_message_drafts_reviewed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_drafts")),
    )
    op.create_index(
        "ix_message_drafts_lead_created",
        "message_drafts",
        ["lead_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_message_drafts_account_idempotency", "message_drafts", ["account_id", "idempotency_key"], unique=True
    )
    op.create_table(
        "prospect_signals",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("signal_key", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("state IN ('unknown','detected','not_detected')", name=op.f("ck_prospect_signals_state")),
        sa.ForeignKeyConstraint(
            ["account_id"], ["accounts.id"], name=op.f("fk_prospect_signals_account_id_accounts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_prospect_signals_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["prospect_sources.id"],
            name=op.f("fk_prospect_signals_source_id_prospect_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospect_signals")),
    )
    op.create_index(
        "ix_prospect_signals_lead_key",
        "prospect_signals",
        ["lead_id", "signal_key", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.add_column("leads", sa.Column("vertical", sa.String(), nullable=True))
    op.add_column("leads", sa.Column("city", sa.String(), nullable=True))
    op.add_column("leads", sa.Column("website", sa.String(), nullable=True))
    op.add_column(
        "leads", sa.Column("match_keys", postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False)
    )
    op.add_column("leads", sa.Column("review_status", sa.String(), nullable=True))
    op.add_column("leads", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("leads", sa.Column("reviewed_by_user_id", sa.UUID(), nullable=True))
    # Alembic does not detect CHECK constraints on existing tables: written by hand.
    # Short name "review_status"; the naming convention prefixes it with ck_leads_.
    op.create_check_constraint(
        "review_status", "leads", "review_status IS NULL OR review_status IN ('pending','approved','rejected')"
    )
    op.create_index(
        "ix_leads_account_review",
        "leads",
        ["account_id", "review_status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND review_status IS NOT NULL"),
    )
    op.create_index("ix_leads_match_keys_gin", "leads", ["match_keys"], unique=False, postgresql_using="gin")
    op.create_foreign_key(
        op.f("fk_leads_reviewed_by_user_id_users"),
        "leads",
        "users",
        ["reviewed_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_leads_review_status"), "leads", type_="check")
    op.drop_constraint(op.f("fk_leads_reviewed_by_user_id_users"), "leads", type_="foreignkey")
    op.drop_index("ix_leads_match_keys_gin", table_name="leads", postgresql_using="gin")
    op.drop_index(
        "ix_leads_account_review",
        table_name="leads",
        postgresql_where=sa.text("deleted_at IS NULL AND review_status IS NOT NULL"),
    )
    op.drop_column("leads", "reviewed_by_user_id")
    op.drop_column("leads", "reviewed_at")
    op.drop_column("leads", "review_status")
    op.drop_column("leads", "match_keys")
    op.drop_column("leads", "website")
    op.drop_column("leads", "city")
    op.drop_column("leads", "vertical")
    op.drop_index("ix_prospect_signals_lead_key", table_name="prospect_signals")
    op.drop_table("prospect_signals")
    op.drop_index("uq_message_drafts_account_idempotency", table_name="message_drafts")
    op.drop_index("ix_message_drafts_lead_created", table_name="message_drafts")
    op.drop_table("message_drafts")
    op.drop_index("uq_prospect_sources_listing_version", table_name="prospect_sources")
    op.drop_index("ix_prospect_sources_lead", table_name="prospect_sources")
    op.drop_table("prospect_sources")
    op.drop_index("ix_prospect_scores_lead_created", table_name="prospect_scores")
    op.drop_table("prospect_scores")
    op.drop_index("uq_score_versions_account_version", table_name="score_versions")
    op.drop_index("ix_score_versions_account_hash", table_name="score_versions")
    op.drop_table("score_versions")
    op.drop_index("ix_usage_records_account_created", table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index("uq_suppression_entries_identity", table_name="suppression_entries")
    op.drop_table("suppression_entries")
    # ### end Alembic commands ###
