import { CheckCircle, Envelope, Key, PaperPlaneTilt, Prohibit, Shield, ShieldCheck, Sparkle, Warning, WhatsappLogo, XCircle } from "@phosphor-icons/react";
import { api } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";
import { useAsync } from "@/lib/outreach";
import { ErrorBlock, LoadingBlock } from "@/components/outreach/States";

// Every status on this page is computed by the server from its real configuration (GET /settings/integrations).
// Nothing here is a hard-coded "ACTIVE": a missing key or package shows up as such, with the reason.

const TONES = {
  ok: { chip: "chip-success", Icon: CheckCircle },
  info: { chip: "chip-ink", Icon: ShieldCheck },
  warn: { chip: "chip-warn", Icon: XCircle },
  danger: { chip: "chip-danger", Icon: Prohibit },
};

export default function Settings() {
  const { user, org } = useAuth();
  const { data: s, error, loading, reload } = useAsync(() => api.get("/settings/integrations").then((r) => r.data), []);

  return (
    <div className="p-6 md:p-10 max-w-4xl space-y-8" data-testid="settings-page">
      <div>
        <div className="mono-accent">// control.panel</div>
        <h1 className="text-4xl font-black tracking-tighter">Settings</h1>
        <p className="text-[#6B6B66] mt-1">Organization profile and the live status of this server&apos;s integrations.</p>
      </div>

      <section className="surface p-6 space-y-4">
        <div className="flex items-center gap-2">
          <Shield size={18} className="text-[#DC2626]" />
          <h2 className="font-display text-xl font-bold">Profile</h2>
        </div>
        <div className="grid md:grid-cols-2 gap-4">
          <Row label="operator.name" value={user?.full_name} />
          <Row label="email" value={user?.email} mono />
          <Row label="role" value={user?.role} mono />
          <Row label="organization" value={org?.name} />
          <Row label="plan" value={org?.plan} mono />
          <Row label="org.id" value={org?.id} mono truncate />
        </div>
      </section>

      <section className="surface p-6 space-y-4" data-testid="integrations">
        <div className="flex items-center gap-2">
          <Key size={18} className="text-[#0F172A]" />
          <h2 className="font-display text-xl font-bold">Integrations</h2>
        </div>
        {loading && !s && <LoadingBlock label="Reading the server configuration…" />}
        {error && <ErrorBlock message={error} onRetry={reload} />}
        {s && <Integrations s={s} />}
      </section>
    </div>
  );
}

function Integrations({ s }) {
  const ai = s.ai;
  const out = s.outreach;
  const hooks = s.webhooks;
  const missing = [];
  if (!s.sendgrid_configured) missing.push("SENDGRID_API_KEY and SENDGRID_FROM_EMAIL");
  if (!s.twilio_account_sid_configured) missing.push("TWILIO_ACCOUNT_SID (starts with AC) and TWILIO_AUTH_TOKEN");
  if (!out.sender_configured) missing.push("OUTREACH_SENDER_NAME, _COMPANY, _ADDRESS and _EMAIL");
  if (!out.smtp_configured) missing.push("SMTP_HOST, SMTP_USERNAME and SMTP_PASSWORD (real prospect e-mail)");
  if (!hooks.twilio_signature_ready) missing.push("TWILIO_AUTH_TOKEN (webhook signature)");
  if (!hooks.sendgrid_signature_ready) missing.push("SENDGRID_WEBHOOK_PUBLIC_KEY");

  let outreachTone = "info";
  let outreachLabel = "DRY-RUN: NOTHING LEAVES THE SYSTEM";
  if (out.kill_switch) {
    outreachTone = "danger";
    outreachLabel = "HALTED BY THE KILL SWITCH";
  } else if (!out.dry_run && !out.smtp_configured) {
    outreachTone = "danger";
    outreachLabel = "LIVE FLAG ON BUT SMTP INCOMPLETE: SENDS ARE REFUSED";
  } else if (!out.dry_run && out.sandbox) {
    outreachTone = "warn";
    outreachLabel = "LIVE · SANDBOX: ALLOWLISTED RECIPIENTS ONLY";
  } else if (!out.dry_run) {
    outreachTone = "warn";
    outreachLabel = "LIVE · REAL E-MAIL TO APPROVED PROSPECTS";
  }

  return (
    <>
      <IntegrationRow
        icon={Sparkle}
        name="AI composer"
        description={
          ai.active
            ? "Messages are generated by the model."
            : `No model is called: the composer returns a fixed template. Reason: ${ai.reason}.`
        }
        tone={ai.active ? "ok" : "warn"}
        statusLabel={ai.active ? "LIVE · MODEL CALLED" : "TEMPLATE ONLY"}
        details={[
          ["api.key", ai.key_configured ? "configured" : "not set"],
          ["emergentintegrations", ai.library_available ? "installed" : "not installed"],
        ]}
        testId="row-ai"
      />
      <IntegrationRow
        icon={Envelope}
        name="SendGrid e-mail"
        description="E-mail sent by campaigns and the message composer, with open and click tracking."
        tone={s.sendgrid_configured ? "ok" : "warn"}
        statusLabel={s.sendgrid_configured ? "CONFIGURED" : "NOT CONFIGURED (MOCK DISPATCH)"}
        details={[["from.email", s.sendgrid_from_email || "not set"]]}
        testId="row-sendgrid"
      />
      <IntegrationRow
        icon={WhatsappLogo}
        name="Twilio WhatsApp"
        description="Outbound WhatsApp, only to contacts who opted in. Falls back to mock dispatch when not configured."
        tone={s.twilio_account_sid_configured ? "ok" : "warn"}
        statusLabel={s.twilio_account_sid_configured ? "CONFIGURED" : "NOT CONFIGURED (MOCK DISPATCH)"}
        details={[["from.number", s.twilio_whatsapp_from || "not set"]]}
        testId="row-twilio"
      />
      <IntegrationRow
        icon={PaperPlaneTilt}
        name="Prospect outreach"
        description="Drafts and dispatch for approved prospects. Limits and the pause apply to every send path."
        tone={outreachTone}
        statusLabel={outreachLabel}
        details={[
          ["sender.identity", out.sender_configured ? "configured" : "not configured"],
          ["sender.email", out.sender_email || "not set"],
          ["FEATURE_LIVE_SENDING", out.live_sending_flag ? "on" : "off"],
          ["smtp.host", out.smtp_configured ? out.smtp_host : "not configured"],
          ["OUTREACH_SANDBOX", out.sandbox ? `on (${out.allowlist_size} allowed)` : "off"],
        ]}
        testId="row-outreach"
      />
      <IntegrationRow
        icon={ShieldCheck}
        name="Webhook signatures"
        description={`Inbound provider events must be signed. ${
          hooks.production ? "In production an unsigned or unverifiable call is rejected." : "Outside production, unsigned calls are accepted (local mock mode)."
        }`}
        tone={hooks.twilio_signature_ready && hooks.sendgrid_signature_ready ? "ok" : "warn"}
        statusLabel={hooks.twilio_signature_ready && hooks.sendgrid_signature_ready ? "BOTH VERIFIED" : "INCOMPLETE"}
        details={[
          ["twilio.signature", hooks.twilio_signature_ready ? "ready" : "no auth token"],
          ["twilio.webhook_url", hooks.twilio_webhook_url_set ? "set" : "not set"],
          ["sendgrid.signature", hooks.sendgrid_signature_ready ? "ready" : "no public key"],
        ]}
        testId="row-webhooks"
      />
      {missing.length > 0 ? (
        <p className="text-sm text-[#92400E] bg-[#FFFBEB] border border-[#F59E0B]/40 rounded-md p-3 flex gap-2" data-testid="missing-config">
          <Warning size={16} className="shrink-0 mt-0.5" />
          <span>Not configured on this server: {missing.join("; ")}. Set them in the server environment (see backend/.env.example).</span>
        </p>
      ) : (
        <p className="mono-accent text-[#999995]">// every integration above is configured on this server.</p>
      )}
    </>
  );
}

function Row({ label, value, mono, truncate }) {
  return (
    <div>
      <div className="mono-accent">{label}</div>
      <div className={`mt-1 ${mono ? "font-mono text-sm" : "font-display font-semibold"} ${truncate ? "truncate" : ""}`}>
        {value || "—"}
      </div>
    </div>
  );
}

function IntegrationRow({ icon: Icon, name, description, tone, statusLabel, details = [], testId }) {
  const { chip, Icon: StatusIcon } = TONES[tone] || TONES.warn;
  return (
    <div className="surface p-5 bg-[#FAFAF7]" data-testid={testId}>
      <div className="flex items-start gap-4">
        <Icon size={24} weight="duotone" className="text-[#DC2626] mt-1" />
        <div className="flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <h3 className="font-display font-semibold">{name}</h3>
            <span className={`chip ${chip}`} data-testid={`${testId}-status`}>
              <StatusIcon size={10} weight="fill" /> {statusLabel}
            </span>
          </div>
          <p className="text-sm text-[#6B6B66] mt-1">{description}</p>
          {details.length > 0 && (
            <div className="mt-3 grid md:grid-cols-2 gap-2 text-xs">
              {details.map(([k, v]) => (
                <div key={k} className="flex gap-2 font-mono">
                  <span className="text-[#999995]">{k}:</span>
                  <span className="text-[#1a1a1a] truncate">{v}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
